import React, { useState, useEffect, useRef } from 'react';
import { X, Save, Link, Calendar } from 'lucide-react';
import toast from 'react-hot-toast';
import clsx from 'clsx';

interface ConnectNodesDialogProps {
  isOpen: boolean;
  onClose: () => void;
  sourceNodeId: string;
  targetNodeId: string;
  sourceNodeLabel: string;
  targetNodeLabel: string;
  sourceHandle?: string;
  targetHandle?: string;
  onConfirm: (data: {
    relationship: string;
    createEvent: boolean;
    eventTitle?: string;
    eventDate?: string;
    eventDescription?: string;
    eventTypeId?: string;
    customTypeName?: string;
  }) => Promise<void>;
  dagId: string;
}

const ConnectNodesDialog: React.FC<ConnectNodesDialogProps> = ({
  isOpen,
  onClose,
  sourceNodeId,
  targetNodeId,
  sourceNodeLabel,
  targetNodeLabel,
  sourceHandle,
  targetHandle,
  onConfirm,
  dagId
}) => {
  const [relationship, setRelationship] = useState('');
  const [relationshipTypeId, setRelationshipTypeId] = useState<string>('');
  const [isCustomRelationship, setIsCustomRelationship] = useState(true);
  const [relationshipsByCategory, setRelationshipsByCategory] = useState<Record<string, Array<{ id: string; name: string }>>>({});
  const [isLoadingRelationships, setIsLoadingRelationships] = useState(false);
  
  // Event creation fields
  const [createEvent, setCreateEvent] = useState(false);
  const [eventTitle, setEventTitle] = useState('');
  const [eventDate, setEventDate] = useState(new Date().toISOString().split('T')[0]);
  const [eventDescription, setEventDescription] = useState('');
  const [selectedEventTypeId, setSelectedEventTypeId] = useState('');
  const [isCustomType, setIsCustomType] = useState(false);
  const [customTypeName, setCustomTypeName] = useState('');
  const [eventTypes, setEventTypes] = useState<Array<{ id: string; name: string; icon: string; color: string }>>([]);
  const [isLoadingTypes, setIsLoadingTypes] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Fetch relationships and event types - only when dialog opens
  useEffect(() => {
    if (!isOpen) return;

    async function fetchRelationships() {
      try {
        setIsLoadingRelationships(true);
        const res = await fetch('/api/relationships');
        if (res.ok) {
          const data = await res.json();
          // Convert to new format if needed (backward compatibility)
          const converted: Record<string, Array<{ id: string; name: string }>> = {};
          Object.entries(data.relationshipsByCategory || {}).forEach(([category, rels]) => {
            converted[category] = Array.isArray(rels) && rels.length > 0 && typeof rels[0] === 'object' && 'id' in rels[0]
              ? rels as Array<{ id: string; name: string }>
              : (rels as string[]).map(name => ({ id: '', name })); // Fallback for old format
          });
          setRelationshipsByCategory(converted);
        }
      } catch (error) {
        console.error('Failed to fetch relationships:', error);
      } finally {
        setIsLoadingRelationships(false);
      }
    }

    async function fetchEventTypes() {
      try {
        setIsLoadingTypes(true);
        const res = await fetch('/api/event-types');
        if (res.ok) {
          const data = await res.json();
          setEventTypes(data.eventTypes || []);
          // Set first event type as default only if not already set
          if (data.eventTypes && data.eventTypes.length > 0) {
            setSelectedEventTypeId((prev) => prev || data.eventTypes[0].id);
          }
        }
      } catch (error) {
        console.error('Failed to fetch event types:', error);
      } finally {
        setIsLoadingTypes(false);
      }
    }

    fetchRelationships();
    fetchEventTypes();
  }, [isOpen]); // Only depend on isOpen

  // Reset form when dialog opens/closes
  useEffect(() => {
    if (!isOpen) {
      setRelationship('');
      setIsCustomRelationship(true);
      setCreateEvent(false);
      setEventTitle('');
      setEventDate(new Date().toISOString().split('T')[0]);
      setEventDescription('');
      setSelectedEventTypeId('');
      setIsCustomType(false);
      setCustomTypeName('');
      hasAutoGeneratedTitle.current = false; // Reset auto-generation flag
    }
  }, [isOpen]);

  // Auto-update event title when relationship changes (only if title is empty and checkbox is checked)
  // Use a ref to track if we've auto-generated the title to avoid overwriting user input
  const hasAutoGeneratedTitle = useRef(false);
  
  useEffect(() => {
    if (createEvent && relationship.trim() && !hasAutoGeneratedTitle.current) {
      const autoTitle = `${sourceNodeLabel} → ${targetNodeLabel}: ${relationship}`;
      setEventTitle(autoTitle);
      hasAutoGeneratedTitle.current = true;
    }
    // Reset flag when relationship or createEvent changes
    if (!createEvent || !relationship.trim()) {
      hasAutoGeneratedTitle.current = false;
    }
  }, [relationship, createEvent, sourceNodeLabel, targetNodeLabel]);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!relationship.trim()) {
      toast.error('Please enter a relationship label');
      return;
    }

    if (createEvent && !eventTitle.trim()) {
      toast.error('Please enter an event title');
      return;
    }

    if (createEvent && !isCustomType && !selectedEventTypeId) {
      toast.error('Please select an event type');
      return;
    }

    if (createEvent && isCustomType && !customTypeName.trim()) {
      toast.error('Please enter a custom event type name');
      return;
    }

    setIsSubmitting(true);
    try {
      // If custom relationship, save it to the database and get its ID
      let finalRelationshipTypeId = relationshipTypeId;
      if (isCustomRelationship && relationship.trim()) {
        try {
          // Determine category based on relationship content (simple heuristic)
          let relationshipCategory = 'General';
          const relLower = relationship.toLowerCase();
          if (relLower.includes('payment') || relLower.includes('tender') || relLower.includes('contract') || relLower.includes('financial') || relLower.includes('money')) {
            relationshipCategory = 'Financial';
          } else if (relLower.includes('testified') || relLower.includes('witness') || relLower.includes('statement')) {
            relationshipCategory = 'Legal';
          } else if (relLower.includes('meeting') || relLower.includes('discussion') || relLower.includes('conversation')) {
            relationshipCategory = 'Personal';
          } else if (relLower.includes('report') || relLower.includes('document') || relLower.includes('evidence')) {
            relationshipCategory = 'Documentary';
          }

          const createRelRes = await fetch('/api/relationships', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              name: relationship.trim(),
              category: relationshipCategory
            })
          });

          if (createRelRes.ok) {
            const newRel = await createRelRes.json();
            finalRelationshipTypeId = newRel.relationship.id;
            console.log('✅ Created custom relationship:', newRel.relationship.name, 'with ID:', finalRelationshipTypeId);
          }
        } catch (error) {
          console.error('Error saving custom relationship:', error);
          // Non-critical - relationship will still be used as custom (no ID)
        }
      }

      await onConfirm({
        relationship: relationship.trim(),
        relationshipTypeId: finalRelationshipTypeId || undefined,
        createEvent,
        eventTitle: createEvent ? eventTitle.trim() : undefined,
        eventDate: createEvent ? eventDate : undefined,
        eventDescription: createEvent ? eventDescription.trim() : undefined,
        eventTypeId: createEvent && !isCustomType ? selectedEventTypeId : undefined,
        customTypeName: createEvent && isCustomType ? customTypeName.trim() : undefined,
      });
      onClose();
    } catch (error) {
      console.error('Failed to create connection:', error);
      toast.error('Failed to create connection');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleRelationshipSelect = (rel: string) => {
    setRelationship(rel);
    setIsCustomRelationship(false);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="bg-background rounded-2xl shadow-2xl w-full max-w-md overflow-hidden flex flex-col max-h-[90vh] border border-border">
        {/* Header */}
        <div className="px-6 py-4 border-b border-border flex items-center justify-between bg-muted/20">
          <div>
            <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
              <Link size={20} className="text-primary" />
              Define Connection
            </h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              {sourceNodeLabel} → {targetNodeLabel}
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-muted rounded-lg text-muted-foreground hover:text-foreground smooth-transition"
            title="Close (Esc)"
          >
            <X size={18} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6 space-y-4">
          {/* Relationship Label */}
          <div className="space-y-2">
            <label className="text-sm font-semibold text-foreground">
              Relationship Label <span className="text-destructive">*</span>
            </label>
            
            {/* Relationship Type Toggle */}
            <div className="flex gap-2 mb-2">
              <button
                type="button"
                onClick={() => setIsCustomRelationship(false)}
                className={clsx(
                  "flex-1 px-3 py-2 rounded-lg text-sm font-medium transition-colors",
                  !isCustomRelationship
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:bg-muted/80"
                )}
              >
                From List
              </button>
              <button
                type="button"
                onClick={() => setIsCustomRelationship(true)}
                className={clsx(
                  "flex-1 px-3 py-2 rounded-lg text-sm font-medium transition-colors",
                  isCustomRelationship
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:bg-muted/80"
                )}
              >
                Custom
              </button>
            </div>

            {!isCustomRelationship ? (
              <div className="space-y-2">
                {isLoadingRelationships ? (
                  <div className="px-4 py-3 bg-muted rounded-lg text-muted-foreground text-sm">
                    Loading relationships...
                  </div>
                ) : (
                  <div className="max-h-48 overflow-y-auto space-y-1 border border-border rounded-lg p-2">
                    {Object.entries(relationshipsByCategory).map(([category, rels]) => (
                      <div key={category} className="space-y-1">
                        <div className="text-xs font-semibold text-muted-foreground px-2 py-1 uppercase tracking-wide">
                          {category.replace('_', ' ')}
                        </div>
                        {rels.map((rel) => (
                          <button
                            key={rel.id || rel.name}
                            type="button"
                            onClick={() => handleRelationshipSelect(rel.id || rel.name)}
                            className={clsx(
                              "w-full text-left px-3 py-2 rounded-md text-sm transition-colors",
                              relationship === rel.name
                                ? "bg-primary text-primary-foreground"
                                : "hover:bg-muted text-foreground"
                            )}
                          >
                            {rel.name}
                          </button>
                        ))}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              <input
                type="text"
                value={relationship}
                onChange={(e) => setRelationship(e.target.value)}
                placeholder="Enter relationship label..."
                className="w-full px-4 py-2.5 bg-background border border-border rounded-lg text-foreground focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all"
                autoFocus
              />
            )}
          </div>

          {/* Create Event Checkbox */}
          <div className="flex items-start gap-3 p-4 bg-muted/30 border border-border rounded-lg">
            <input
              type="checkbox"
              id="createEvent"
              checked={createEvent}
              onChange={(e) => setCreateEvent(e.target.checked)}
              className="mt-1 w-4 h-4 rounded border-border text-primary focus:ring-primary focus:ring-offset-0"
            />
            <div className="flex-1 space-y-2">
              <label htmlFor="createEvent" className="text-sm font-semibold text-foreground cursor-pointer flex items-center gap-2">
                <Calendar size={16} className="text-primary" />
                Create Event from Connection
              </label>
              <p className="text-xs text-muted-foreground">
                Optionally create an event that documents this relationship
              </p>
            </div>
          </div>

          {/* Event Fields (shown when checkbox is checked) */}
          {createEvent && (
            <div className="space-y-4 p-4 bg-primary/5 border border-primary/20 rounded-lg">
              <div className="space-y-2">
                <label className="text-sm font-semibold text-foreground">
                  Event Title <span className="text-destructive">*</span>
                </label>
                <input
                  type="text"
                  value={eventTitle}
                  onChange={(e) => setEventTitle(e.target.value)}
                  placeholder="Enter event title..."
                  className="w-full px-4 py-2.5 bg-background border border-border rounded-lg text-foreground focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all"
                />
              </div>

              <div className="space-y-2">
                <label className="text-sm font-semibold text-foreground">Date</label>
                <input
                  type="date"
                  value={eventDate}
                  onChange={(e) => setEventDate(e.target.value)}
                  className="w-full px-4 py-2.5 bg-background border border-border rounded-lg text-foreground focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all"
                />
              </div>

              {/* Event Type */}
              <div className="space-y-2">
                <div className="flex items-center gap-2 mb-2">
                  <label className="text-sm font-semibold text-foreground">
                    Event Type <span className="text-destructive">*</span>
                  </label>
                  <button
                    type="button"
                    onClick={() => {
                      setIsCustomType(!isCustomType);
                      if (!isCustomType) {
                        setSelectedEventTypeId('');
                        setCustomTypeName('');
                      }
                    }}
                    className="text-xs text-primary hover:underline"
                  >
                    {isCustomType ? 'Select from list' : 'Use custom type'}
                  </button>
                </div>
                
                {isCustomType ? (
                  <input
                    type="text"
                    value={customTypeName}
                    onChange={(e) => setCustomTypeName(e.target.value)}
                    placeholder="Enter custom event type..."
                    className="w-full px-4 py-2.5 bg-background border border-border rounded-lg text-foreground focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all"
                  />
                ) : (
                  <>
                    {isLoadingTypes ? (
                      <div className="px-4 py-2.5 bg-background border border-border rounded-lg text-muted-foreground text-sm">
                        Loading event types...
                      </div>
                    ) : (
                      <select
                        value={selectedEventTypeId}
                        onChange={(e) => setSelectedEventTypeId(e.target.value)}
                        className="w-full px-4 py-2.5 bg-background border border-border rounded-lg text-foreground focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all cursor-pointer"
                      >
                        <option value="">Select event type...</option>
                        {eventTypes.map((type) => (
                          <option key={type.id} value={type.id}>
                            {type.name}
                          </option>
                        ))}
                      </select>
                    )}
                  </>
                )}
              </div>

              <div className="space-y-2">
                <label className="text-sm font-semibold text-foreground">Description</label>
                <textarea
                  value={eventDescription}
                  onChange={(e) => setEventDescription(e.target.value)}
                  placeholder="Optional description..."
                  rows={3}
                  className="w-full px-4 py-2.5 bg-background border border-border rounded-lg text-foreground focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all resize-none"
                />
              </div>
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-3 pt-4 border-t border-border">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 px-4 py-2.5 bg-muted text-muted-foreground rounded-lg font-medium hover:bg-muted/80 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting || !relationship.trim() || (createEvent && (!eventTitle.trim() || (!isCustomType && !selectedEventTypeId) || (isCustomType && !customTypeName.trim())))}
              className="flex-1 px-4 py-2.5 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                  Creating...
                </>
              ) : (
                <>
                  <Save size={16} />
                  Create Connection
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default ConnectNodesDialog;
